### ISSUE TITLE
Syntax highlighting 

### ISSUE THREAD

**Issue by kasyanov-ms** [canisbos/CustomReader#2]
Hello. The Reader's code contains tags like this `<pre lang="java">`. Is it possible to modify the extension in order to highlight keywords using [this method](https://highlightjs.org/usage/)?

**Comment by canisbos** [comment]
I'm not sure what you mean by "Reader's code contains tags like...." Are you talking about the source code of Reader itself? Or are you referring to <pre> tags on a page that is viewed in Reader?

If you are talking about tags on a page, please give me an example page URL. I have not seen tags such as <pre lang="java">.

**Comment by kasyanov-ms** [comment]
My fault. I saw that tag on [this page](https://www.raywenderlich.com/116580/introduction-to-android-activities-tutorial) in the reader state. That's why I mistakenly thought Reader had learned to recognize the programming languages. But it was only derived from the full page. Thank you for your extension!
