### ISSUE TITLE
Safari 12 requires install from the Safari Extension Gallery

### ISSUE THREAD

**Issue by BasO** [canisbos/CustomReader#3]
Hi, I love this extension but sadly it won't install in Safari 12, i.e. MacOS 10.14 Mojave, because Safari 12 removes support for developer-signed .safariextz Safari extension files. Per Apple's release notes:

> Support for developer-signed .safariextz Safari Extensions in Safari 12 on macOS has been removed. They no longer appear in Safari preferences and cannot be enabled. On first launch users will receive a warning notification and these extension will not load.

Instead, they have to be installed from the Safari Extensions Gallery. See https://developer.apple.com/safari/whats-new/ .

One workaround is to open & run the CustomReader extension manually in Extension Builder, but this needs to be done for every new Safari session and preferences are not saved between sessions.

Canisbos, are you (financially/principally) able to submit CustomReader to the Safari Extension Gallery? I'd love to keep using it.

**Comment by canisbos** [comment]
Hi. I'm sorry. I lack the bandwidth or passion to learn how to write Safari app extensions. In all likelihood, I will not be porting any of these extensions to the new platform.

**Comment by SnarkNerd** [comment]
Bummer! Thanks for letting us know (and for making it originally)!
